Repository openHPI/xikolo-android, pull requests merged in 2019-11, with the labels that each got.

#184 Fix for back navigation in MainActivity
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
Labels: bug

#185 Adaptive Icons
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_circle.xml
  app/src/main/res/values/colors.xml
  app/src/moochouse/res/drawable/ic_launcher_icon.xml
  app/src/moochouse/res/values/colors_apptheme.xml
  app/src/openhpi/res/drawable/ic_launcher_icon.xml
  app/src/opensap/res/drawable/ic_launcher_icon.xml
  app/src/opensap/res/values/colors_apptheme.xml
  app/src/openwho/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/openwho/res/mipmap-anydpi-v26/ic_launcher_circle.xml
  app/src/openwho/res/mipmap-hdpi/ic_launcher_icon.png
  app/src/openwho/res/mipmap-mdpi/ic_launcher_icon.png
  app/src/openwho/res/mipmap-xhdpi/ic_launcher_icon.png
  app/src/openwho/res/mipmap-xxhdpi/ic_launcher_icon.png
  app/src/openwho/res/mipmap-xxxhdpi/ic_launcher_icon.png
  app/src/openwho/res/values/colors_apptheme.xml
Labels: enhancement

#186 Compatibility with Android 10 (API29)
  .travis.yml
  build.gradle
Labels: enhancement

#191 v3.0 CourseListAdapter crashes
  app/src/main/java/de/xikolo/controllers/base/BaseMetaRecyclerViewAdapter.kt
  app/src/main/java/de/xikolo/controllers/course/ItemListAdapter.kt
  app/src/main/java/de/xikolo/controllers/course/SectionListAdapter.kt
  app/src/main/java/de/xikolo/controllers/main/AnnouncementListAdapter.kt
  app/src/main/java/de/xikolo/controllers/main/CertificateListAdapter.kt
  app/src/main/java/de/xikolo/controllers/main/ChannelListAdapter.kt
  app/src/main/java/de/xikolo/utils/MetaSectionList.kt
  app/src/test/java/de/xikolo/testing/unit/MetaSectionListTest.kt
Labels: bug, help wanted

#193 More v3 Hotfixes
  app/src/main/java/de/xikolo/controllers/video/VideoDescriptionFragment.kt
  app/src/main/java/de/xikolo/controllers/video/VideoItemPlayerActivity.kt
  app/src/main/java/de/xikolo/controllers/video/VideoItemPlayerFragment.kt
  app/src/main/java/de/xikolo/controllers/video/VideoStreamPlayerActivity.kt
  app/src/main/java/de/xikolo/controllers/video/VideoStreamPlayerFragment.kt
  app/src/main/java/de/xikolo/utils/extensions/StorageExtensions.kt
Labels: bug

#194 Fix crash when in PiP
  app/src/main/java/de/xikolo/controllers/video/base/BaseVideoPlayerActivity.kt
Labels: bug

#188 Implemented Helpdesk
  app/src/main/java/de/xikolo/config/FeatureConfig.kt
  app/src/main/java/de/xikolo/controllers/announcement/AnnouncementActivity.kt
  app/src/main/java/de/xikolo/controllers/base/BaseMetaRecyclerViewAdapter.kt
  app/src/main/java/de/xikolo/controllers/channels/ChannelDetailsActivity.kt
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
  app/src/main/java/de/xikolo/controllers/dialogs/ConfirmCancelDialog.kt
  app/src/main/java/de/xikolo/controllers/dialogs/CreateTicketDialog.kt
  app/src/main/java/de/xikolo/controllers/dialogs/HelpdeskTopicAdapter.kt
  app/src/main/java/de/xikolo/controllers/dialogs/HelpdeskTopicDialog.kt
  app/src/main/java/de/xikolo/controllers/downloads/DownloadsActivity.kt
  app/src/main/java/de/xikolo/controllers/login/LoginActivity.java
  app/src/main/java/de/xikolo/controllers/login/SsoLoginActivity.java
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
  app/src/main/java/de/xikolo/controllers/section/CourseItemsActivity.kt
  app/src/main/java/de/xikolo/controllers/settings/SettingsActivity.kt
  app/src/main/java/de/xikolo/controllers/settings/SettingsFragment.kt
  app/src/main/java/de/xikolo/controllers/video/base/BaseVideoPlayerActivity.kt
  app/src/main/java/de/xikolo/controllers/webview/WebViewActivity.java
  app/src/main/java/de/xikolo/models/Ticket.kt
  app/src/main/java/de/xikolo/models/dao/CourseDao.kt
  app/src/main/java/de/xikolo/network/ApiService.kt
  app/src/main/java/de/xikolo/network/ApiServiceInterface.kt
  app/src/main/java/de/xikolo/network/jobs/CreateTicketJob.kt
  app/src/main/java/de/xikolo/utils/extensions/DateExtensions.kt
  app/src/main/java/de/xikolo/viewmodels/helpdesk/HelpdeskTopicViewModel.kt
  app/src/main/java/de/xikolo/viewmodels/helpdesk/TicketViewModel.kt
  app/src/main/res/drawable-hdpi/ic_nav_help.png
  app/src/main/res/drawable-mdpi/ic_nav_help.png
  app/src/main/res/drawable-xhdpi/ic_nav_help.png
  app/src/main/res/drawable-xxhdpi/ic_nav_help.png
  app/src/main/res/drawable-xxxhdpi/ic_nav_help.png
  app/src/main/res/layout/dialog_helpdesk_create_ticket.xml
  app/src/main/res/layout/dialog_helpdesk_topic_selection.xml
  app/src/main/res/layout/item_header_secondary.xml
  app/src/main/res/layout/item_helpdesk_topic_list.xml
  app/src/main/res/menu/helpdesk.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: feature
