Repository openHPI/xikolo-android, pull requests merged in 2020-08, with the labels that each got.

#227 Implementation of Shortcuts
  app/src/main/java/de/xikolo/App.kt
  app/src/main/java/de/xikolo/config/Feature.kt
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
  app/src/main/java/de/xikolo/storages/RecentCoursesStorage.kt
  app/src/main/java/de/xikolo/utils/ShortcutUtil.kt
  app/src/main/res/drawable/ic_shortcut_my_courses.xml
  app/src/test/java/de/xikolo/testing/unit/RecentCoursesTest.kt
Labels: feature

#268 Fix deeplink issues
  app/src/androidTest/java/de/xikolo/testing/instrumented/unit/DeepLinkingUtilTest.kt
  app/src/main/java/de/xikolo/utils/DeepLinkingUtil.kt
Labels: bug

#270 Fix Deeplink Navigation
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
Labels: bug

#271 Fix invalid formatting strings
  app/src/main/res/values-fr/strings.xml
Labels: bug, firebase

#272 Replace Bypass with Markwon as used markdown library
  app/dependencies.gradle.kts
  app/src/main/java/de/xikolo/utils/extensions/TextViewExtensions.kt
  app/src/main/res/layout/fragment_course_description.xml
  app/src/main/res/raw/notices.xml
Labels: bug, enhancement
