Repository openHPI/xikolo-android, pull requests merged in 2020-11, with the labels that each got.

#293 Allow back navigation in Discussions WebView
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
  app/src/main/java/de/xikolo/controllers/webview/WebViewFragment.kt
Labels: enhancement

#294 Fix vertical scrolling in nested WebViews
  app/src/main/java/de/xikolo/views/NestedScrollWebView.kt
Labels: bug, enhancement

#295 Refactor Intent opening logic
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/xikolo/controllers/channels/ChannelDetailsFragment.kt
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
  app/src/main/java/de/xikolo/controllers/dialogs/UnsupportedIntentDialog.kt
  app/src/main/java/de/xikolo/controllers/helper/DownloadViewHelper.kt
  app/src/main/java/de/xikolo/controllers/main/CourseListFragment.kt
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
  app/src/main/java/de/xikolo/download/DownloadItem.kt
  app/src/main/java/de/xikolo/download/filedownload/FileDownloadItem.kt
  app/src/main/java/de/xikolo/utils/extensions/IntentExtensions.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, question

#298 Update dependencies
  Gemfile.lock
  app/dependencies.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies
