Repository openHPI/xikolo-android, pull requests merged in 2020-09, with the labels that each got.

#274 Possible fix for #265 Realm: IllegalStateException
  app/src/main/java/de/xikolo/models/dao/VideoDao.kt
  app/src/main/java/de/xikolo/viewmodels/section/CourseItemsViewModel.kt
Labels: bug, firebase

#276 Android 11
  .travis.yml
  Dangerfile
  Gemfile.lock
  app/dependencies.gradle.kts
  app/src/main/java/de/xikolo/controllers/helper/WebViewHelper.kt
  app/src/main/java/de/xikolo/services/DownloadService.kt
  app/src/main/java/de/xikolo/states/ConnectivityStateLiveData.kt
  app/src/main/java/de/xikolo/utils/extensions/ShareExtensions.kt
  app/src/main/res/layout/activity_blank_tabs.xml
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  fastlane/README.md
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#277 Update ExoPlayer to Version 2.12.0
  app/dependencies.gradle.kts
  app/src/main/java/de/xikolo/views/ExoPlayerVideoView.kt
Labels: dependencies

#279 Migrate ViewPagers to ViewPager2 and fix workarounds
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
  app/src/main/java/de/xikolo/controllers/section/CourseItemsActivity.kt
  app/src/main/java/de/xikolo/views/PositionRetainingTabLayout.kt
  app/src/main/res/layout/activity_blank_tabs.xml
Labels: enhancement

#281 Fix crashes in new ViewPager
  app/src/main/java/de/xikolo/controllers/section/CourseItemsActivity.kt
  app/src/main/java/de/xikolo/download/filedownload/FileDownloadItem.kt
Labels: bug
