Repository openHPI/xikolo-android, pull requests merged in 2020-10, with the labels that each got.

#283 Dependency Updates
  Gemfile.lock
  app/dependencies.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: dependencies

#285 Reload course model on CourseActivity refresh
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
Labels: enhancement

#290 Move and redeclare ShareBroadcastReceiver
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/xikolo/receivers/ShareBroadcastReceiver.kt
  app/src/main/java/de/xikolo/utils/extensions/ShareExtensions.kt
Labels: bug

#288 Add intent query declaration for Android 11
  app/src/main/AndroidManifest.xml
Labels: bug
