Repository openHPI/xikolo-android, pull requests merged in 2020-04, with the labels that each got.

#230 New Feature Config
  app/build.gradle
  app/src/androidTest/java/de/xikolo/testing/instrumented/mocking/MockingData.kt
  app/src/androidTest/java/de/xikolo/testing/instrumented/mocking/MockingInterceptor.kt
  app/src/androidTest/java/de/xikolo/testing/instrumented/ui/ChannelsTest.kt
  app/src/androidTest/java/de/xikolo/testing/instrumented/unit/DeepLinkingUtilTest.kt
  app/src/main/java/de/xikolo/config/BuildFlavor.kt
  app/src/main/java/de/xikolo/config/BuildType.kt
  app/src/main/java/de/xikolo/config/CastOptionsProvider.kt
  app/src/main/java/de/xikolo/config/Config.kt
  app/src/main/java/de/xikolo/config/Feature.kt
  app/src/main/java/de/xikolo/config/FeatureConfig.kt
  app/src/main/java/de/xikolo/controllers/base/BaseCourseListAdapter.kt
  app/src/main/java/de/xikolo/controllers/dialogs/HelpdeskTopicDialog.kt
  app/src/main/java/de/xikolo/controllers/downloads/DownloadsFragment.kt
  app/src/main/java/de/xikolo/controllers/helper/CourseNavigationHelper.kt
  app/src/main/java/de/xikolo/controllers/helper/VideoSettingsHelper.kt
  app/src/main/java/de/xikolo/controllers/login/LoginFragment.kt
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
  app/src/main/java/de/xikolo/controllers/settings/SettingsFragment.kt
  app/src/main/java/de/xikolo/controllers/video/VideoStreamPlayerFragment.kt
  app/src/main/java/de/xikolo/controllers/video/base/BaseVideoPlayerActivity.kt
  app/src/main/java/de/xikolo/models/Course.java
  app/src/main/java/de/xikolo/utils/DeepLinkingUtil.kt
  app/src/main/java/de/xikolo/utils/LanalyticsUtil.kt
  app/src/main/java/de/xikolo/utils/extensions/ResourcesExtensions.kt
  app/src/main/java/de/xikolo/viewmodels/channel/ChannelViewModel.kt
  app/src/main/java/de/xikolo/viewmodels/main/ChannelListViewModel.kt
  app/src/main/java/de/xikolo/viewmodels/main/CourseListViewModel.kt
  app/src/main/java/de/xikolo/views/CourseFilterView.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/features.xml
  app/src/main/res/values/keys.xml
  app/src/main/res/values/languages.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
  app/src/moochouse/res/values-de/features.xml
  app/src/moochouse/res/values-de/strings.xml
  app/src/moochouse/res/values/colors.xml
  app/src/moochouse/res/values/features.xml
  app/src/moochouse/res/values/strings.xml
  app/src/moochouse/res/values/strings_apptheme.xml
  app/src/openhpi/res/values-de/features.xml
  app/src/openhpi/res/values-de/strings.xml
  app/src/openhpi/res/values/colors.xml
  app/src/openhpi/res/values/features.xml
  app/src/openhpi/res/values/strings.xml
  app/src/openhpi/res/values/strings_apptheme.xml
  app/src/opensap/res/values-de/features.xml
  app/src/opensap/res/values-de/strings.xml
  app/src/opensap/res/values-de/strings_apptheme.xml
  app/src/opensap/res/values/colors.xml
  app/src/opensap/res/values/features.xml
  app/src/opensap/res/values/strings.xml
  app/src/opensap/res/values/strings_apptheme.xml
  app/src/openwho/res/values-de/strings_apptheme.xml
  app/src/openwho/res/values/colors.xml
  app/src/openwho/res/values/features.xml
  app/src/openwho/res/values/strings.xml
  app/src/openwho/res/values/strings_apptheme.xml
Labels: refactoring

#232 Migrate to APIv4
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
  app/src/main/java/de/xikolo/controllers/main/ProfileFragment.kt
  app/src/main/java/de/xikolo/controllers/section/VideoPreviewFragment.kt
  app/src/main/java/de/xikolo/models/Channel.java
  app/src/main/java/de/xikolo/models/CourseProgress.java
  app/src/main/java/de/xikolo/models/Profile.java
  app/src/main/java/de/xikolo/models/Quiz.java
  app/src/main/java/de/xikolo/models/SectionProgress.java
  app/src/main/java/de/xikolo/models/Video.java
  app/src/main/java/de/xikolo/models/dao/ItemDao.kt
  app/src/main/java/de/xikolo/models/migrate/RealmSchemaMigration.java
  app/src/main/java/de/xikolo/utils/extensions/CastExtensions.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: schema change

#236 v3.2 Hotfixes
  app/src/main/java/de/xikolo/controllers/login/LoginFragment.kt
  app/src/main/java/de/xikolo/controllers/main/CourseListFragment.kt
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
  app/src/main/java/de/xikolo/controllers/video/VideoStreamPlayerFragment.kt
  app/src/main/java/de/xikolo/models/dao/ChannelDao.kt
  app/src/main/java/de/xikolo/utils/extensions/IntentExtensions.kt
  app/src/main/java/de/xikolo/utils/extensions/ToastExtensions.kt
  app/src/main/java/de/xikolo/viewmodels/main/NavigationViewModel.kt
  app/src/main/java/de/xikolo/viewmodels/section/CourseItemsViewModel.kt
Labels: bug, firebase

#234 Refactor External Links in Navigation
  app/build.gradle
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
  app/src/main/java/de/xikolo/utils/extensions/ResourcesExtensions.kt
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/features.xml
  app/src/main/res/values/strings.xml
  app/src/openhpi/res/values/features.xml
  app/src/openhpi/res/values/strings.xml
  app/src/opensap/res/values/features.xml
  app/src/openwho/res/values/features.xml
  lint.xml
Labels: refactoring

#233 Lernen.cloud Flavor
  .travis.yml
  app/build.gradle
  app/src/lernencloud/debug/google-services.json
  app/src/lernencloud/ic_launcher-playstore.png
  app/src/lernencloud/release/google-services.json
  app/src/lernencloud/res/drawable/ic_launcher_icon.xml
  app/src/lernencloud/res/drawable/login_header_v2.png
  app/src/lernencloud/res/drawable/title.png
  app/src/lernencloud/res/layout/view_toolbar.xml
  app/src/lernencloud/res/mipmap-hdpi/ic_launcher.png
  app/src/lernencloud/res/mipmap-hdpi/ic_launcher_circle.png
  app/src/lernencloud/res/mipmap-hdpi/ic_splash.png
  app/src/lernencloud/res/mipmap-mdpi/ic_launcher.png
  app/src/lernencloud/res/mipmap-mdpi/ic_launcher_circle.png
  app/src/lernencloud/res/mipmap-mdpi/ic_splash.png
  app/src/lernencloud/res/mipmap-xhdpi/ic_launcher.png
  app/src/lernencloud/res/mipmap-xhdpi/ic_launcher_circle.png
  app/src/lernencloud/res/mipmap-xhdpi/ic_splash.png
  app/src/lernencloud/res/mipmap-xxhdpi/ic_launcher.png
  app/src/lernencloud/res/mipmap-xxhdpi/ic_launcher_circle.png
  app/src/lernencloud/res/mipmap-xxhdpi/ic_splash.png
  app/src/lernencloud/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/lernencloud/res/mipmap-xxxhdpi/ic_launcher_circle.png
  app/src/lernencloud/res/mipmap-xxxhdpi/ic_splash.png
  app/src/lernencloud/res/values-de/features.xml
  app/src/lernencloud/res/values-de/strings.xml
  app/src/lernencloud/res/values/colors.xml
  app/src/lernencloud/res/values/features.xml
  app/src/lernencloud/res/values/strings.xml
  app/src/main/res/drawable-hdpi/ic_nav_schulcloud.png
  app/src/main/res/drawable-mdpi/ic_nav_schulcloud.png
  app/src/main/res/drawable-xhdpi/ic_nav_schulcloud.png
  app/src/main/res/drawable-xxhdpi/ic_nav_schulcloud.png
  app/src/main/res/drawable-xxxhdpi/ic_nav_schulcloud.png
  fastlane/Appfile
  signing.properties
  xikolo-android.jks
Labels: new platform

#238 Gradle Builds with Kotlin DSL
  Dangerfile
  app/build.gradle
  app/build.gradle.kts
  app/dependencies.gradle
  app/dependencies.gradle.kts
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Flavors.kt
  lanalytics/build.gradle
  lanalytics/build.gradle.kts
  settings.gradle
  settings.gradle.kts
Labels: refactoring

#239 Disallow enrollments in not enrollable courses
  app/src/main/java/de/xikolo/controllers/base/BaseCourseListAdapter.kt
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
  app/src/main/res/layout/view_enroll_button.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug
