Repository openHPI/xikolo-android, pull requests merged in 2020-03, with the labels that each got.

#215 Make LTI selftests available after the deadline passed
  app/src/main/java/de/xikolo/controllers/section/LtiExerciseFragment.kt
Labels: bug

#195 channel teaser video implemented
  app/src/main/java/de/xikolo/controllers/base/CollapsingToolbarViewModelActivity.kt
  app/src/main/java/de/xikolo/controllers/channels/ChannelCourseListAdapter.kt
  app/src/main/java/de/xikolo/controllers/channels/ChannelDetailsActivity.kt
  app/src/main/java/de/xikolo/controllers/channels/ChannelDetailsFragment.kt
  app/src/main/java/de/xikolo/models/Channel.java
  app/src/main/java/de/xikolo/models/migrate/RealmSchemaMigration.java
  app/src/main/java/de/xikolo/viewmodels/channel/ChannelViewModel.kt
  app/src/main/res/layout/content_channel_description.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  build.gradle
Labels: schema change

#214 Workaround for bundling VideoStream- and VideoItemPlayerFragment
  app/src/main/java/de/xikolo/controllers/video/VideoItemPlayerActivity.kt
  app/src/main/java/de/xikolo/controllers/video/VideoItemPlayerFragment.kt
  app/src/main/java/de/xikolo/controllers/video/VideoStreamPlayerActivity.kt
  app/src/main/java/de/xikolo/controllers/video/VideoStreamPlayerFragment.kt
Labels: discuss

#220 Hotfix for intent chooser extension crash
  app/src/main/java/de/xikolo/controllers/course/CourseActivity.kt
  app/src/main/java/de/xikolo/controllers/section/LtiExerciseFragment.kt
  app/src/main/java/de/xikolo/controllers/section/PeerAssessmentFragment.kt
  app/src/main/java/de/xikolo/utils/extensions/IntentExtensions.kt
Labels: bug, firebase

#224 Bugfixes
  app/src/main/java/de/xikolo/controllers/login/LoginFragment.kt
  app/src/main/java/de/xikolo/controllers/main/MainActivity.kt
  app/src/main/java/de/xikolo/controllers/video/VideoStreamPlayerFragment.kt
Labels: bug, firebase

#228 Course Filter
  app/src/main/java/de/xikolo/controllers/base/BaseActivity.kt
  app/src/main/java/de/xikolo/controllers/main/CourseListFragment.kt
  app/src/main/java/de/xikolo/models/Course.java
  app/src/main/java/de/xikolo/models/dao/ChannelDao.kt
  app/src/main/java/de/xikolo/models/dao/CourseDao.kt
  app/src/main/java/de/xikolo/viewmodels/main/ChannelListViewModel.kt
  app/src/main/java/de/xikolo/viewmodels/main/CourseListViewModel.kt
  app/src/main/java/de/xikolo/viewmodels/shared/ChannelListDelegate.kt
  app/src/main/java/de/xikolo/views/CourseFilterClassifierView.kt
  app/src/main/java/de/xikolo/views/CourseFilterView.kt
  app/src/main/res/drawable-hdpi/ic_filter.png
  app/src/main/res/drawable-mdpi/ic_filter.png
  app/src/main/res/drawable-xhdpi/ic_filter.png
  app/src/main/res/drawable-xxhdpi/ic_filter.png
  app/src/main/res/drawable-xxxhdpi/ic_filter.png
  app/src/main/res/layout/fragment_course_list.xml
  app/src/main/res/layout/view_course_filter_classifier.xml
  app/src/main/res/layout/view_spinner_item.xml
  app/src/main/res/menu/refresh.xml
  app/src/main/res/menu/search.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/moochouse/res/values/strings_apptheme.xml
  app/src/openhpi/res/values-de/strings_apptheme.xml
  app/src/openhpi/res/values/strings_apptheme.xml
  app/src/opensap/res/values-de/strings_apptheme.xml
  app/src/opensap/res/values/strings_apptheme.xml
  app/src/openwho/res/values/strings_apptheme.xml
Labels: feature
