Repository openHPI/xikolo-android, pull requests merged in 2021-06, with the labels that each got.

#312 Fix VideoPreviewFragment.kt line 267
  app/src/main/java/de/xikolo/controllers/section/VideoPreviewFragment.kt
Labels: bug 🐛

#311 Fix RequestManagerRetriever.java line 348
  app/src/main/java/de/xikolo/utils/extensions/TextViewExtensions.kt
Labels: bug 🐛

#302 Subtitle support for Cast
  app/src/main/java/de/xikolo/utils/extensions/CastExtensions.kt
  app/src/main/res/values/themes.xml
Labels: feature 📦

#313 Update dependencies
  app/dependencies.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: internal 🔨
